# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'surechigaiApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'RealmSwift'

  # Pods for surechigaiApp

  target 'surechigaiAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'surechigaiAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
